### ISSUE TITLE
Crash on loading member browser

### ISSUE THREAD

**Issue by kwy2** [WorksOfBarry/ILEditor#102]
I opened the Member Browser window, put in my library and QRPGLESRC, hit the search icon.

The browser window says Loading...

A popup window appears that tells me ILEditor has stopped working.
![image](https://user-images.githubusercontent.com/34299243/50366044-a4a18d80-0534-11e9-8345-014df576cab0.png)

**Comment by worksofliam** [comment]
Hi @kwy2 - sorry for the late reply.

Try this: https://github.com/WorksOfBarry/ILEditor/issues/73#issuecomment-378927312

Let me know if it does or doesn't help.

Many thanks,
Liam Barry
