### ISSUE TITLE
SQL COBOL syntax highlighting

### ISSUE THREAD

**Issue by frenkmo** [WorksOfBarry/ILEditor#107]
I suggest to add syntax highlighting to SQLCBLLE member  (Cobol SQL)
Thanks

**Comment by worksofliam** [comment]
Is a pretty simple fix. Will get around to it soon.

**Comment by worksofliam** [comment]
Fixed and will be available in the next release.

3fd68c62d4a61052b4add53312d75339a01a6cf1
