### ISSUE TITLE
Silent install options

### ISSUE THREAD

**Issue by ghost** [WorksOfBarry/ILEditor#108]
Is there a way to do a silent install? We would like to push this and updates to some users.

**Comment by worksofliam** [comment]
Hi @Kaosfury 

Silent install has been requested by a few people lately but is not yet something I can provide.

You can, however, build the application yourself using Visual Studio to create the application and then you can manually deploy the files.

**Comment by ghost** [comment]
Thank you. I'm not a developer of any kind, so I cannot do that myself, but I will talk to some of our devs and see if any of them can.

Thanks for the suggestion.
