### ISSUE TITLE
QSYS Browser remove entry

### ISSUE THREAD

**Issue by prsbrc** [WorksOfBarry/ILEditor#117]
Hi. I have a question:
How can i remove a entry from the qsys browser?
thx und greets

**Comment by worksofliam** [comment]
I believe you can use the delete key? It's been a while.

**Comment by prsbrc** [comment]
No sorry, the delete key is not working :-(

**Comment by prsbrc** [comment]
It works on subentries like QRPGLESRC.
When every subentry is deleted the mainentry will be removed on next start so it will works :-)

**Comment by worksofliam** [comment]
Ahh! I knew it worked somewhere :)

Thanks!
