### ISSUE TITLE
V7.4 Member browsing don't work

### ISSUE THREAD

**Issue by karlxfritz** [WorksOfBarry/ILEditor#119]
On 7.4 OSi I got the message "no members found" while member browsing. On 7.1  it's ok.
ILEditor 1.6.8

**Comment by tooq2bstr8** [comment]
Hi karlxfritz,

I had the same problem.
For me following setting works:
Try to change in ILEditor in you connections setting of your IBMi the FTP Data Connection Tye to PASV.

Best regards
Volker

**Comment by LOGIC-stack** [comment]
Thanks, works now.

**Comment by karlxfritz** [comment]
Thanks, works now.
