### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by worksofliam** [WorksOfBarry/ILEditor#14]
Should we work on adding multilingual support?

https://www.codeproject.com/Tips/580043/How-to-make-a-multi-language-application-in-Csharp

**Comment by prsbrc** [comment]
Yes, please. Because for me here in Austria it's sometimes necessary to write some comments in local language (with ä/ö/ü/ß etc)

**Comment by worksofliam** [comment]
@prsbrc What happens when you use those characters and save the source? Do they retain or not?

**Comment by prsbrc** [comment]
![ileeditor](https://user-images.githubusercontent.com/31685593/34484244-bdb45262-efc3-11e7-9cb5-e85566b7b201.png)
![seu](https://user-images.githubusercontent.com/31685593/34484245-bdce4dd4-efc3-11e7-8baa-7b6f50a42be4.png)

Hey, yes they retain in my source.
I think this is only a conversion-problem between the program and the src-pf ccsid (1141)

**Comment by worksofliam** [comment]
@prsbrc 

I did a simple test and created a SRC-PF with CCSID(273) - I also changed my 5250 window to use 273 and it looks like it's converter okay to me.

![image](https://user-images.githubusercontent.com/3708366/34484622-c581518a-efbd-11e7-8d48-4c0699b61a2a.png)

![image](https://user-images.githubusercontent.com/3708366/34484599-96aeb2bc-efbd-11e7-8f6c-64798c350ccd.png)

**Comment by prsbrc** [comment]
Hmmm... the only thing i can say is that i've got an src-pf with ccsid 1141 and if i type my "ü" into the ileEditor in src-pf the ü was converted to the "letter-salad" i've posted above :-)

**Comment by worksofliam** [comment]
Oh, that is very odd. Can you confirm that your host session is in CCSID 1141?

**Comment by prsbrc** [comment]
Yes, i can confirm this. My host session ccsid is 1141, system ccsid is 1141 and of corse the src-pf is also 1141  :-)

**Comment by prsbrc** [comment]
![ws](https://user-images.githubusercontent.com/31685593/34485670-1099bd66-efcc-11e7-816a-98abd65444b6.png)

**Comment by worksofliam** [comment]
Okay, I have recreated the problem. Not sure how something like this happens when there is only a 1 character difference between 273 and 1141 :)

![image](https://user-images.githubusercontent.com/3708366/34485832-6a89067c-efc4-11e7-8aac-a288ad0197aa.png)

Looks like it could be converting the two byte character from Windows to two separate bytes on IBM i when uploading.

**Comment by worksofliam** [comment]
Current work around: use the actual hex code for the value in your RPG, which I think is: 

* `x'FC'` for `ü` (lowercase)
* `x'DC'` for `Ü` (uppercase)

For example: `mychar = 'Hi' + x'FC' + 'there';`

**Comment by worksofliam** [comment]
Note to self: C# can handle converting to EBCDIC. It may be worth converting the source locally and then uploading the output from the conversion.

https://msdn.microsoft.com/en-us/library/system.text.encodinginfo.getencoding(v=vs.110).aspx

**Comment by prsbrc** [comment]
Thx for trying to fix it :-)

**Comment by worksofliam** [comment]
Okay, so the issue is that the file is uploading as ASCII only - there is no way to change the way FTP works.

That means, these are the current valid characters (basically no accents available):
![image](https://user-images.githubusercontent.com/3708366/34491847-03565824-efdd-11e7-8661-9be400a8f21a.png)

What can change is ILEditor. To support the users code page, we must transfer everything in binary and do all the conversions on the users local machine.

On download:
1. Download member in `BINARY` (so CCSID 37, or 297, or 1141, or whatever) to temp file
2. On the fly translate that `byte[]` into UTF8 (might be possible with `Encoding.Convert`?) and then save into `SOURCEDIR`

On save: 
1. Translate UTF8 to `byte[]`, and write to a temp file
2. Upload temp file with `BINARY`

This does mean writing a library/class to convert back and forth from EBCDIC and UTF8.

**Comment by worksofliam** [comment]
@prsbrc Good news! You can ignore all of that, because it turns out IBM i FTP support ASCII Extended and I just wasn't using ASCII extended. 

It's taken two lines of code to fix this issue!! Will get a commit and release out for you tonight.

**Comment by prsbrc** [comment]
Great job. Will try it tomorow :)

**Comment by worksofliam** [comment]
The commit is in and a release has been made. Please retest and reopen if the issue persists.

**Comment by prsbrc** [comment]
Hey. Write to the IBMi works fine but when i load a source from the IBMi it don't convert correctly:
![iledit](https://user-images.githubusercontent.com/31685593/34515343-00656f20-f072-11e7-90a8-e457cfd1b89b.png)
![seu](https://user-images.githubusercontent.com/31685593/34515344-009cb69c-f072-11e7-8889-a9c06edf0895.png)

**Comment by worksofliam** [comment]
@prsbrc A temp release has been made. I forgot to make it read the file in the correct encoding! Please let me know if this works or not.

**Comment by prsbrc** [comment]
Hey, thanks. This temp-release works fine :-)

**Comment by worksofliam** [comment]
@prsbrc Great, thanks!

Closing as fixed in cad8e73c9baa7ef8990160bef4bad22b70d866ad.
