### ISSUE TITLE
No members found

### ISSUE THREAD

**Issue by prsbrc** [WorksOfBarry/ILEditor#21]
Good Morning.
Since last update i can't fetch any members :-(
![tree_browser](https://user-images.githubusercontent.com/31685593/34760393-f6660f7a-f5df-11e7-9336-8fc661fe5935.png)
Joblog from the ftp-job is in german but shows no error.

**Comment by worksofliam** [comment]
@prsbrc Sorry this is happening to you. I cannot re-create it. Instead I have added something so you can access the FTP log.

1. Try and open the source-physical file again in the Tree Browser
2. Open the FTP Log by going to Help->Session FTP Log
3. Paste the contents of the opened document here so I can see the problem.

Cheers!

**Comment by prsbrc** [comment]
Hey.

Here we go :-)

greets
Christian

**Comment by worksofliam** [comment]
@prsbrc Are you able to see if this file exists? Can you also paste the content of it here if it does? 

`C:\Users\DV0109\AppData\Roaming\ILEditor\S44C0107\QTEMP\QRPGLESRC\QRPGLESRC.mbr`

Cheers,
Liam

**Comment by prsbrc** [comment]
Yes, wait a minute ... ahm this file is empty

**Comment by prsbrc** [comment]
[0110T1422.txt](https://github.com/WorksOfBarry/ILEditor/files/1618912/0110T1422.txt)

**Comment by worksofliam** [comment]
@prsbrc I have released another fix to print more information when downloading a file. Can you repeat the FTP Log steps:

1. Try and open the source-physical file again in the Tree Browser
2. Open the FTP Log by going to Help->Session FTP Log
3. Paste the contents of the opened document here so I can see the problem.

Cheers

**Comment by prsbrc** [comment]
[0110T1422.txt](https://github.com/WorksOfBarry/ILEditor/files/1618930/0110T1422.txt)

**Comment by worksofliam** [comment]
@prsbrc I have released yet *another* change to the log file. Can you repeat the steps one more time? :)

1. Restart ILEditor and update
2. Try and open the source-physical file again in the Tree Browser
3. Open the FTP Log by going to Help->Session FTP Log
4. Paste the contents of the opened document here so I can see the problem.

Cheers!
Liam

**Comment by prsbrc** [comment]
So, i have done the update and repeat the tree-browser:
[0110T1437.txt](https://github.com/WorksOfBarry/ILEditor/files/1618955/0110T1437.txt)
![mbr](https://user-images.githubusercontent.com/31685593/34775634-26e75904-f614-11e7-977d-21041dec467e.png)

**Comment by worksofliam** [comment]
@prsbrc 

Looks like there is something causing a hang in the new FTP library we are using. I am assuming this because if you compare our files at the bottom:

Your file:
```
# OpenPassiveDataStream(AutoPassive, "RETR /QSYS.lib/QTEMP.lib/QRPGLESRC.file/QRPGLESRC.mbr", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (!!!30050!).
```

My file:
```
# OpenPassiveDataStream(AutoPassive, "RETR /QSYS.lib/QTEMP.lib/QRPGLESRC.file/QRPGLESRC.mbr", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||11384|).
Status:   Connecting to ***:11384
Command:  RETR /QSYS.lib/QTEMP.lib/QRPGLESRC.file/QRPGLESRC.mbr
Response: 150 Retrieving member QRPGLESRC in file QRPGLESRC in library QTEMP.
Response: 150-NAMEFMT set to 1.
Status:   Disposing FtpSocketStream...
Response: 226 File transfer completed successfully.
```

They are different. Looks like yours is not even printing anything useful. Am I able to gain access to this system (or a similar one) to try and recreate?

Liam

**Comment by prsbrc** [comment]
Sorry, there is no direct way to connect from outside.
Maximum via TeamViewer and my PC :-)
Maybe tomorrow?

**Comment by worksofliam** [comment]
@prsbrc One last thing to check might be this in Windows:

![image](https://user-images.githubusercontent.com/3708366/34776929-749e79c4-f610-11e7-9036-8e6efcff9b8d.png)

Edit: Just disabled it and it made no difference. Ignore this

**Comment by prsbrc** [comment]
My windoofs-firewall is deactiveted :-)
Manual ftp from dos-box runs perfect

**Comment by worksofliam** [comment]
I am assuming it might be a CCSID issue - so until I can get access to a system with CCSID 273 I cannot fix it in anyway :( 

I will revert back to the working version and move this new stuff to a branch to fix it for you.

**Comment by prsbrc** [comment]
Thanks a lot. Maybe when the pub400 is back online :-) ?
Greets
Christian

**Comment by worksofliam** [comment]
@prsbrc Restart and download the latest update. It's back to the normal code base now.

I have moved the code I was working on out of the `master` branch into [`newgtp`](https://github.com/WorksOfBarry/ILEditor/tree/newgtp).

I am very excited for when pub400 is back up :)
