### ISSUE TITLE
ILE Build Tools for RDi

### ISSUE THREAD

**Issue by worksofliam** [WorksOfBarry/ILEditor#25]
Originally an RFE for RDi, but could be useful for ILEditor.

https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=50961

**Comment by WorksOfLiam** [comment]
I imagine if there was a project tool in the Toolbox it would have a tree view which might look something like this

```
ProjectA
 - Build settings
   - Setup library list (would allow you to edit the library list of the build)
   - Build commands (would open up a tool to edit the build commands)
 - Project Library
   - Add SPF (When clicked, will allow you to add (if already exists) or create an SPF)
   - QRPGLESRC
      - MYFILE.rpgle
   - QDDSSRC
     - Add member (when clicked you would add (if already exists) or create a new member in the selected SPF)
   + QSQLSRC
```

* Project SPF would only show items that have been added to the project. For example, if you create a project over an existing library, you will not see any of the existing SPFs or members unless you add them to the project listing. If the member already exists, then it will not create it.

**Comment by worksofliam** [comment]
Idea no. 1

* New toolbox item which is a treelist.
* First treelist node is `New Project`, which opens a new window
  * New windows asks you what you want to create: `ILE Module`, `ILE Program`
  * After selection starting files will be generated

For ILE program:

An ILE program object will create a normal PGM object out of modules.

* Provide Project name
* Provide initial source: `RPG`, `C`, maybe eventually `C++`
* Provide program name (10 characters)
* Project properties will allow you to bind additional module dependencies which are made outside of this project - you may also be able to specify a different project to 'depend' on
* This will create two SPFs in the project: `SOURCE`, `HEADERS`
  * A source file with the program name will be created in the newly created SPF `SOURCE` with the initial source template

**Comment by worksofliam** [comment]
Progress has been made today. The project outline looks like this:
![image](https://user-images.githubusercontent.com/3708366/35200634-eb02c726-ff09-11e7-9c3f-4257f3f5ee0a.png)

`Project Settings` will allow to to:
* Select the build library where all the source and objects will be placed
* Specify any local projects that need to be built before the the current project has been built (kind of like a local dependancy)
* Specify any existing *MOD to include in the `CRTPGM` command (for ILE Program build only)

`Project Build` will submit the build. Must also make an F5 binding

**Comment by worksofliam** [comment]
Projects is now implemented to a good level.

* There are two types of project. ILE Program and ILE Modules. ILE Service Program is soon to come
* Both Program and Modules projects create the modules, but the Program project will create a PGM object with `CRTPGM`
* All source is stored locally and each source in the `Sources` folder is compiled into it's own module (if possible, otherwise SQL statement, or DSPF obj, or CMD obj, for example)
* You can specify local project dependancies in the Project Settings, which allow you specify which other local projects need to be build before building the current build.
* For Program and Service Program project: you can also specify modules outside of the project that need to be included in the CRTPGM.

**Comment by worksofliam** [comment]
https://github.com/WorksOfBarry/ILEditor/wiki/ILEditor---projects-feature-annoucement

**Comment by worksofliam** [comment]
Feature not to be made into master branch any time soon. I don't think this feature is important to our users, but may be more important when people are interested in doing more distributed development.
