### ISSUE TITLE
IFS support

### ISSUE THREAD

**Issue by worksofliam** [WorksOfBarry/ILEditor#29]
Must support IFS stream files.

It will be up to the user to handle compiling CL, DDS, etc from the IFS (perhaps by using `CRTFRMSTMF`)

* [x] Opening stream files (this also introduced opening local files)
* [x] Saving stream files (this also introduced saving local files)
* [x] New Connection Settings: `homeDir`, `buildLib` for when compiling from IFS. `homeDir` will be used as the current directory when compiling and `buildLib` is the library we will build the object into
* [x] Ability to compile stream files
* [x] Error listing is working as expected, except that clicking on error throws an error saying to open the file - must fix.
* [x] Browser for the IFS. Will use `homeDir` as root directory

#### Mid priority
* [ ] Files be stored on local machine in same folder structure on remote machine.
* [x] Ability to shortcuts to other folders instead of just the `homeDir`

#### Low priority

* [x] Python syntax highlighting (light & dark)
* [ ] PHP syntax highlighting (light & dark)
* [ ] JavaScript syntax highlighting (light & dark)

**Comment by Gailor** [comment]
Nice

**Comment by worksofliam** [comment]
Priority stuff is finished. Low priority can happen whenever.

Some images of stuff implemented:

![](https://i.imgur.com/NhIxDbR.png)

![](https://i.imgur.com/eI3YoDL.png)

![](https://i.imgur.com/Hz3YAGX.png)

**Comment by worksofliam** [comment]
Would be useful if someone could work on the PHP & JavaScript highlight, for both light and dark themes.
