### ISSUE TITLE
FTP Connection - Keep alive or reconnect automatically and FTP log Timestamp

### ISSUE THREAD

**Issue by bvstone** [WorksOfBarry/ILEditor#34]
I find that if my IBM i FTP server has an inactivity time out set (CGGFTPA Inactivity timeout . . . . . . . INACTTIMO      300 ), ILEditor won't automatically reconnect unless I stop and restart ILEditor.

I am assuming the FTP server timeout is what is causing me not to refresh my member list as I don't see the active FTP job any longer on the system.

The FTP log in ILEditor also doesn't have a timestamp in it, so it is hard to tell what commands are failing and why.  That would be a nice addition.

**Comment by worksofliam** [comment]
Yes, I have noticed the timeout. This is something I will look into.

Cheers,
Liam

**Comment by worksofliam** [comment]
KeepAlive functionality to be added in 1.2.3.0.
