### ISSUE TITLE
Error produced when double clicking error listing entry when line number > 308

### ISSUE THREAD

**Issue by bvstone** [WorksOfBarry/ILEditor#35]
When clicking on an error after compiling I got an error saying there was an unhandled exception. It seems to be related to the line number the error happened on.  The error was on line 1811 in this case.

I actually looked further into this and the error number reported by ILEditor in this case was wrong.  I have communicated info with Liam about this.

**Comment by worksofliam** [comment]
I found that this issue occurs with the SQL-precompiler using `*LVL2` which has includes inside of it. I made a fix in 23884e8be1f2dcef38e10ab5dba8279144b76f57.

Please retest and re-open if the issue persists.
