### ISSUE TITLE
Default Spool library and object

### ISSUE THREAD

**Issue by aaronbartell** [WorksOfBarry/ILEditor#36]
Currently you have to modify connection settings before you can display your own spool files.  Would be good if this was configured by default.

As a stop gap, you could fill it with QGPL/QPRINT which is most likely what many have as their default.

Love, 
Bacon

**Comment by worksofliam** [comment]
I will add QGPL/QPRINT as the default option for next release. 

It's also possible to get the user's current output queue using `USER_INFO`(?) in SQL.

Thanks!

**Comment by worksofliam** [comment]
Default output queue QGPL/QPRINT has been defined for 1.3.0.0+
