### ISSUE TITLE
Simultaneous multiple connections

### ISSUE THREAD

**Issue by aaronbartell** [WorksOfBarry/ILEditor#37]
Right now I can only connect to one system at a time.  If I need to connect to another system it requires closing my work on the current system and connecting to another.  Would be nice if I could have multiple systems connected simultaneously.

Love,
Bacon

**Comment by worksofliam** [comment]
I can't promise I will implement this. Right now, the way around this is by starting a second ILEditor window and opening a second instance.

I will keep this in mind.

**Comment by worksofliam** [comment]
After some thought, with the state of the current architecture this is not really possible.

With that being said, I will close this issue.
