### ISSUE TITLE
Ability to search inside of opened spool file

### ISSUE THREAD

**Issue by aaronbartell** [WorksOfBarry/ILEditor#38]
When I open a spool file it is often the case I need to search for specific things.  Currently I have to search with my eyes.  Would be great to have a simple search/find capability.

Love,
Bacon (wrapped in Bacon)

**Comment by worksofliam** [comment]
This one is nice and simple. Expect it in the next release.

Note to self: instead of opening the spool file with a rich text box, open with SourceEditor instead - this will allow a find function.

**Comment by worksofliam** [comment]
Fixed within 1.3.0.0
