### ISSUE TITLE
Build with vs2017 cannot import the following key file Idle.pfx

### ISSUE THREAD

**Issue by NathanielACollier** [WorksOfBarry/ILEditor#4]
I think there is something I'm just not understanding and not a problem with the actual code.  When I first pulled down the repo before Thanksgiving I think I was able to build it.  This week though I can't get past not being able to build with errors about Idle.pfx.  Below are the errors.

`1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3090,5): error MSB3325: Cannot import the following key file: Idle.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_D8A95F77772037F7
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3090,5): error MSB3321: Importing key file "Idle.pfx" was canceled.`

The error makes it seem like there is something maybe I can do with the certificate store to make it go away?  My goal is to be able to find something I can do a pull request on.

**Comment by worksofliam** [comment]
Hey @NathanielACollier 

Generally you won't need to worry about this. I use it when I publish the app. 

To fix this: 
1. go into the project properties within Visual Studio (Project -> ILEditor Properties...),
2. select Signing on the left
3. untick 'Sign the assembly' and build again.

![image](https://user-images.githubusercontent.com/3708366/33380050-c05b8962-d511-11e7-9f37-2e9f547cc3a2.png)

Let me know if you have any more troubles.

**Comment by worksofliam** [comment]
@NathanielACollier Did this resolve your issue?
