### ISSUE TITLE
Hard error when visiting IFS first

### ISSUE THREAD

**Issue by aaronbartell** [WorksOfBarry/ILEditor#40]
ILEditor bombs if the first thing I do is try to view the IFS.  If I first display QSYS.LIB and then IFS then the IFS shows successfully.  

See below screenshot.

![image](https://user-images.githubusercontent.com/106142/36228552-1bbe202a-119a-11e8-9a0c-ba0dbc9fbd92.png)

**Comment by worksofliam** [comment]
Okay, thanks. I am not able to re-create it, but changes have already been made to how the IFS listing works, which you will see in the next release.

**Comment by worksofliam** [comment]
Hi @aaronbartell 

Please retest in the latest version (1.3.0.0) and let me know if it still persists.

Thanks!
Liam

**Comment by worksofliam** [comment]
Re-fixed in 1.3.2.0

**Comment by NK11581** [comment]
Hi Liam,

I am facing issue in first time use. I was able to connect to IBM i but when opening a member it gives an error

"Unable to download member . Please check if it exists and you have access to remote system"


Can you please assist

**Comment by worksofliam** [comment]
@NK11581 Please do not comment on closed issues unless it is relevant to the issue.

See this issue and follow some of the steps: https://github.com/WorksOfBarry/ILEditor/issues/73#issuecomment-378926694
