### ISSUE TITLE
Save ICON now acts as a SAVE-AS

### ISSUE THREAD

**Issue by XpPaul1** [WorksOfBarry/ILEditor#42]
In version 1.3.0.0 when you go to click on the SAVE ICON diskette, it pops a save-as  prompt

Cntrl S still works Okay.

![capture](https://user-images.githubusercontent.com/36519805/36280353-f9e39538-1267-11e8-9278-3349d4c81cc5.PNG)

**Comment by worksofliam** [comment]
Ops! I will fix this now.

**Comment by worksofliam** [comment]
Fixed in 25d6d922bd99a722292b081d097bce4e2aae00a9 and is now available in 1.3.0.1
