### ISSUE TITLE
ILEditor on old OS VRM

### ISSUE THREAD

**Issue by bkoscien** [WorksOfBarry/ILEditor#43]
Hello,

It seems that ILEditor extracts / returns some informations to the client using RUNSQL.
Unfortunately, this command appeared at level 7.1 of the OS.
Actually, I do'nt know if 

In our case, we have more than 250 boxes ranging from 5.3 to 7.3 TR4.
For organisationnal reasons, our tools are always generated and distributed from an  LPAR running at level VRM 540.

I have noticed that the PF-SRC member lists are always generated but nothing is returned to ILEditor due to the lack of RUNSQL command

There are several other 'older' methods to get these informations from DB2i.
Could you consider to add a choice button or another mecanism to select the right extraction method? 

I know this request sounds from another epoch, but it would be great for us.

Thank you
Benoit

**Comment by worksofliam** [comment]
Hi @bkoscien 

Thanks for your interest. Sadly, I have no plans to support anything before 7.1. Having said that, I am more than happy to accept pull requests for supporting older platforms.

While the code will still work on 7.1: I only plan on support 7.1 until its end of life, which then I will only support 7.2 and above: http://ibmiclock.mybluemix.net/

If I had access to a 5.4 box, then my response might have been different. Sorry!

Many thanks,
Liam
