### ISSUE TITLE
Ability to edit hosts before selecting them

### ISSUE THREAD

**Issue by worksofliam** [WorksOfBarry/ILEditor#48]

**Comment by worksofliam** [comment]
Note: would be nice.

**Comment by getfoundational** [comment]
Hi Liam,

This suddenly has become a large issue for me, unless I am missing some work around.  I updated my password on the development system and now none of the existing system connections I have to it will work and there does not seem to be a way to edit that information to adjust the saved password for logon which has rendered those connections/systems unusable for now.

Is there some other way to edit those settings perhaps?

Thank you.

**Comment by worksofliam** [comment]
Hi @getfoundational 

I would suggest selecting Offline Mode before connecting to the system - this will not attempt to connect to the remote system then. When the IDE has launched, go into the Connection Settings and update the password.

I will eventually get around to working on this.

Thanks!

**Comment by getfoundational** [comment]
Thanks!  That works as a good work around.

**Comment by worksofliam** [comment]
This has been implemented. Will be available in 1.6.1.
