### ISSUE TITLE
Project rename [help wanted]

### ISSUE THREAD

**Issue by worksofliam** [WorksOfBarry/ILEditor#5]
Hi

Idle needs to be renamed. I have been putting it off for months, but since I am not a Python developer I never realised that the Python IDE is actually called IDLE as well - this is a bit of an issue.

I need help with name suggestions, so please share some ideas if you have any.

Cheers,
Liam

**Comment by NathanielACollier** [comment]
Here are some.  I don't know how trademarks would affect any of this, so I'm going to put that out there...

ILEEdit

iEdit

**Comment by soberteq** [comment]
Ally, Shapr, DevMate (just anything with Mate, for some reason)

**Comment by jordiwes** [comment]
Ladle :)

**Comment by forstie** [comment]
iEdit

**Comment by RandleBR** [comment]
+1 Ladle !

**Comment by worksofliam** [comment]
Thanks all for the replies - looks like I may use ILEditor - which is a mix of ILEEdit and iEdit.

ILEditor was actually the original name for the project, so should be a matter of only changing a few things.

I will close this issue when all the changes have been put in place - including changes to the website:

[done] worksofbarry.com/idle will redirect to worksofbarry.com/ileditor
[done] The Idle installer will be removed since it will not longer work and a new installer will be provided.
[done] The devnews for the Idle application will be changed to show users to download the latest version, ILEditor.

**Comment by worksofliam** [comment]
All the tasks are done.

There is now a new installer, a new URL + a redirect from the old & all text in the application has been fixed to use ILEditor.

Cheers!
