### ISSUE TITLE
ILEditor through VPN

### ISSUE THREAD

**Issue by Apsoftbe** [WorksOfBarry/ILEditor#50]
Hello Liam,
I'm trying to work with your editor through VPN.
I'm getting Unable to connect ... - Timed out to trying ... after few seconds.
VPN is working because I can open telnet session to system.
Which ports are you using to connect.
Thanks
Peter

**Comment by bvstone** [comment]
I can verify ILEditor works over multiple different types VPNs for me.  So it's possible the client doesn't have FTP server started or it's running on different ports, etc.  The FTP log may give some clues.
