### ISSUE TITLE
Getting error "Unable to download member LIBR1/SOURCEPF.MBR1". Please check it exists and that you have access to the remote system

### ISSUE THREAD

**Issue by venky76v** [WorksOfBarry/ILEditor#52]
Hi Barry,

Don't know if I should be raising this as an issue. I just updated to the latest version of the editor and now I am not able to open any of the sources? It was working on the last version but since the last update, I am getting the error "**Unable to download member LIBR1/SOURCEPF.MBR1". Please check it exists and that you have access to the remote system**"?

Are there any logs that I look to see why I am not able to view any of the sources?

Thanks,
Venky

**Comment by worksofliam** [comment]
Hi @venky76v 

Please follow the steps on this comment and please retest.

https://github.com/WorksOfBarry/ILEditor/issues/26#issuecomment-363849218

Let me know if it persists. What version of the OS are you on?

Thanks,
Liam

**Comment by worksofliam** [comment]
Hi. Please reopen this issue of it persists. Thanks.
