### ISSUE TITLE
First time usage

### ISSUE THREAD

**Issue by bkoscien** [WorksOfBarry/ILEditor#54]
Hello,

Where can we find the list of shortcuts?
Thank you

**Comment by worksofliam** [comment]
There is no user documentation yet. Here is a list off the top of my head:

Ctrl+N - New
Ctrl+O - Open
Ctrl+P - Open previous / Fast search
Ctrl+S - Save
Ctrl+L - Library List Settings
Ctrl+Alt+C - RPG Conversion
Ctrl+Alt+X - CL Formatter
Ctrl+B - Quick Comment
Ctrl+Shift+C - Compile open source

**Comment by bkoscien** [comment]
Thank you
