### ISSUE TITLE
RPG Source conversion - DCL-xx

### ISSUE THREAD

**Issue by bdietz400** [WorksOfBarry/ILEditor#55]
When I take a hunk of "old" code to convert to free-form, a trailing "END-xx;" is "missing(not added)".  It's is easy enough for me to to add after the conversion, just wanted to see your thoughts. 

example

D RtvObjD         Pr                  ExtPgm( 'QUSROBJD' )         
D  RoRcvVar                  32767a         Options( *VarSize )    
D  RoRcvVarLen                  10i 0 Const                        
D  RoFmtNam                      8a   Const                        
D  RoObjNamQ                    20a   Const                        
D  RoObjTyp                     10a   Const                        
D  RoError                   32767a         Options( *VarSize )    

converts to 

       Dcl-PR RtvObjD  ExtPgm( 'QUSROBJD' );
         Dcl-Parm RoRcvVar Char(32767) Options( *VarSize );
         Dcl-Parm RoRcvVarLen Int(10) Const;
         Dcl-Parm RoFmtNam Char(8) Const;
         Dcl-Parm RoObjNamQ Char(20) Const;
         Dcl-Parm RoObjTyp Char(10) Const;
         Dcl-Parm RoError Char(32767) Options( *VarSize );

**Comment by worksofliam** [comment]
Hey @bdietz400

Right now the reason it does this is because the user selects which code they want to convert manually, and therefore we don't add the end-pi incase it's not the end of the interface. The user may only be converting one or two lines.

Thanks,
Liam
