### ISSUE TITLE
Compiles default to PRT01 OutQ

### ISSUE THREAD

**Issue by nbush78** [WorksOfBarry/ILEditor#56]
When compiling a source, the spool file defaults to PRT01 instead of my OutQ defined in connection settings.

**Comment by worksofliam** [comment]
The output queue defined in the connection settings does not choose where to place spool files. It is used to determine where to load spool files from for the Spool Listing.

**Comment by nbush78** [comment]
I found my ileditor job in QSYSWRK
The job is using the QTMFTPS job description, but has PRT01 as the Printer device
The Job Description has Printer device set to *USRPRF
My user profile has the Printer device set to *WRKSTN
Since this job has no workstation it was defaulting to the QPRTDEV system value of PRT01

I changed the Printer device setting for my user profile to another printer that doesn't have an associated writer and this resolved my issue. Hope this info helps others.

**Comment by worksofliam** [comment]
Thanks for sharing this @nbush78!

**Comment by nbush78** [comment]
Correction, even though the job says it is running under my userid in wrkactjob, when you work with the job it is running under QTCP. Will need to think abit before making the Print device change to the QTCP user, so right now I just am running CHGJOB JOB(136170/QTCP/QTFTP00939) PRTDEV(FAKEPRT) on new instances of ileditor.
