### ISSUE TITLE
IFSBrowser directory traversal

### ISSUE THREAD

**Issue by kenwilcox** [WorksOfBarry/ILEditor#57]
Using latest source (SHA ad79952) when I traverse the directories in the IFS Browser past the initial load the last folder in the parent path is coming back from the Client.GetListing(remoteDir).

Example: lets say that I have my home directory set up to /home/source and under that there's a Common folder and under Common there are folders A, B, and C. When the IFSBroswer.cs files_AfterExpand is called I see that e.Node.Tag is /home/source/Common but when I inspect Listing.ToArray in the e.Node.Nodes.AddRange() the Listings show Common/A, Common/B, and Common/C, which just gets added to the Tree View as such. Then when I try to open up that file or directory I get a /home/source/Common/Common/A does not exist, which is true since Common is in the path twice.

I'd love to help out on this, but I'm not sure the best way to attack this. I'm guessing it has something to do with the FluentFTP?

**Comment by worksofliam** [comment]
Yes.. looks like something to do with FluentFTP. Feel free to try make a manual fix, otherwise I will give it a go tomorrow.

Thanks for raising this issue!

**Comment by worksofliam** [comment]
Note for tomorrow, line 80 of IFSBrowser.cs has this: `node.Tag = item.FullName;` - this might be the place to start.

**Comment by kenwilcox** [comment]
I started with that, but I’m not sure how I want to check for a duplicate name because what if the path further down is a legit duplicate name?

I don’t recall having this issue on Friday? It looks like there was 30+ commits since then, I’m not sure what changed.

**Comment by worksofliam** [comment]
@kenwilcox 

A couple of things that might help you is to keep rolling back the commits to find when this issue started happening. I don't have time today but I can start taking a look tomorrow.
