### ISSUE TITLE
QSYS Browser Still shows deleted SPFs

### ISSUE THREAD

**Issue by nbush78** [WorksOfBarry/ILEditor#59]
I did some cleanup within my library and removed some old source physical files. I noticed that they still show in QSYS Browser and don't see a way to refresh or remove a src-pf from the listing.

**Comment by worksofliam** [comment]
Hi @nbush78 

You should select the SPF that is still appearing and use the Delete key to remove them. The listed SPFs are just shortcuts, so removing the shortcut from ILEditor will not delete the SPF on the remote system

Thanks
Liam

**Comment by nbush78** [comment]
Thanks! i was right clicking thinking of getting a menu. never thought to try physical button.
