### ISSUE TITLE
Code Conversion - Data Structures Not Migrated Properly

### ISSUE THREAD

**Issue by getfoundational** [WorksOfBarry/ILEditor#60]
Hi Liam,

I was using ILEditor to convert a program from fixed format to free and noticed that my data structures were not converted properly.  

If I start with this:

`DHEADERDS         e ds                  extname(HEADER) Qualified`

After conversion I get this:
`Dcl-DS HEADERDS         e  extname(HEADER) Qualified;`

But that does not compile and what I really needed was:
```
Dcl-DS HEADERDS
            extname('HEADER') Qualified
end-ds;
```

That does seem like a complex conversion so if that needs fixed manually each time, that's fine too but I wanted to make you aware.

Thank you,
Brian

**Comment by worksofliam** [comment]
Hi @getfoundational 

Can you place the entire fixed-line (with all the correct spacing) so I can recreate this?

Thanks,
Liam

**Comment by getfoundational** [comment]
Pasting in here, even using the code markdown seems to suppress the spaces.  Let's try a text attachment.

[Code-Snip.txt](https://github.com/WorksOfBarry/ILEditor/files/1762683/Code-Snip.txt)

**Comment by paulgfoster** [comment]
Hi Liam,

One more conversion error that I found (v1.5) ....

varying doesn't work for ucs2 fields:

       d myVarUCS        s             32c   varying   // original
       Dcl-S myVarUCS Ucs2(32) varying;	         // converted
       Dcl-S myVarUCS Varucs2(32);                   // should be

character types are fine.

Paul

**Comment by mlstoppa** [comment]
Hi all,
I am using Ileditor 1.6.0.1 and RPG conversion option is no more available. 
Can I ask why? Is there a way to have it back?
Thank you
Lucia

**Comment by worksofliam** [comment]
Hi @mlstoppa 

It is current disabled in the latest release so I can work on improving it.

It had issues and wasn't great at converting everything. In a tool like this, it needs to be all or nothing.

Expect it available again in the future.

Thanks!
Liam

**Comment by worksofliam** [comment]
As a re-write is going to happen and the current conversion is disabled; I am going to close this issue.

Thanks!
Liam
