### ISSUE TITLE
IDE - Save Setup of IDE on Exit and use on Open

### ISSUE THREAD

**Issue by getfoundational** [WorksOfBarry/ILEditor#61]
Hi Liam,

I wanted to ask if the saving of the general setup of the IDE was possible in ILEditor?  Like when I open it and position the various items like Toolbox, QSYS Browser, etc if the sizes, positions, and attributes (like auto hide) of those items should be saved somehow when you close the IDE and reopen it later?

This sort of ties in to Brad's issue of window size, it just expands on it a bit more.

Thank you again,
Brian

**Comment by worksofliam** [comment]
Persistent docking has been added in commit ec31e0edec63492066ef5a66e9908911ffd2a5ca.

It will be available in ILEditor 1.4.4.0
