### ISSUE TITLE
Remove Compile Type  accidently keyed in.

### ISSUE THREAD

**Issue by XpPaul1** [WorksOfBarry/ILEditor#62]
In the compile options, you can create a New compile type or New command.
I have accidentally  keyed in a New Compile Type with the wrong name.  but I don't see a way to remove it.

**Comment by worksofliam** [comment]
Currently there is no way to remove it. This is something I can add to my to do - pull requests are welcome if it's needed sooner.

Thanks!

**Comment by XpPaul1** [comment]
thanks.  Not needed sooner.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
