### ISSUE TITLE
Login Port other than 21

### ISSUE THREAD

**Issue by bluezdood** [WorksOfBarry/ILEditor#64]
We are unable to login due to the inability to use a port other than 21.

**Comment by worksofliam** [comment]
I will add an enhancement so the user is able to specify a port number in the hostname.

Not sure of a timeline, but it will be on my to do list.

Thanks,
Liam

**Comment by worksofliam** [comment]
In host name, allow for both `hostname` and `port`: `hostname:port`

**Comment by worksofliam** [comment]
Ability added in commit e6e55fb2fdce8e0d3906dfed4420f954ed7a7233

Will be available in 1.5.3.
