### ISSUE TITLE
Saving Wrong Member

### ISSUE THREAD

**Issue by bvstone** [WorksOfBarry/ILEditor#66]
Open a member (MEMBER1) to edit.  Edit it.  Don't save it.

Open another member (MEMBER2).  New tab is opened.  

Go back to the first member tab.  Save.  It says "MEMBER2 saved." instead of MEMBER1.  And in checking, it is saving MEMBER2 instead of MEMBER1, even though MEMBER1 is showing and it's tab is highlighted.

**Comment by worksofliam** [comment]
Hi @bvstone 

I am aware of a fix and will look into doing it today at some point.

The work around for now is the select the text area of the tab first and then save.

Thanks,
Liam

**Comment by worksofliam** [comment]
@bvstone 

This issue should be fixed in 1.5.2.0.

Thanks,
Liam
