### ISSUE TITLE
Non-FTP connection methods

### ISSUE THREAD

**Issue by StuBramley** [WorksOfBarry/ILEditor#70]
The tool looks promising however the connection method being based on FTP/FTPS is a show stopper for us being able to adopt it.  We have clients that block FTP at the firewall for security reasons. FTPS is allowed however command execution over FTPS is not - also for security reasons.

**Comment by worksofliam** [comment]
We could one day implement an SSH only version, but the reason we use FTP is for the consistant job and ASCII member conversions.
