### ISSUE TITLE
NO DLCOBJ

### ISSUE THREAD

**Issue by beatony** [WorksOfBarry/ILEditor#72]
Good morning, I noted via FTP log that ILEditor do an ALCOBJ. But when I close the source there is no opposite command DLCOBJ, so member stay locked.
I  don't know if it's my own problem.

**Comment by worksofliam** [comment]
Hi

I was able to recreate this and I must have removed the event handler when playing around with the dock. I have fixed it and the fix will be available in ILEditor 1.5.4.

**Comment by beatony** [comment]
Thanks a lot ! Bye
