### ISSUE TITLE
I don't get a source opened

### ISSUE THREAD

**Issue by moege** [WorksOfBarry/ILEditor#73]
I've wanted to test the ILEditor (v 1.5.4.0). I hope I'm not a complete fool, but I can't open a RPGLE source from our IBM i.
Here my steps that I tried:
1. Open per Member Browser. But when I type in my library and source-pf, I just get the answer "No members found!" (-> I checked it, there are sources in my sandbox-library). 
2. Open it directly by using File -> Open -> Member. There I got the Message "Unable to download member XYZ/QRPGLESRC.MYMBR. Please check it exists and that you have access to the remote system".
(-> I checked it again, there are really some sources - and it's my own library so I do have access)
3. Create a new sourcemember by File -> New -> Member, to check if the connection is correct and I have access to the remote system.
That worked, so I was completly confused, because the connection seems to be correct.

What am I doing wrong? Could you please help me?
Thanks a lot for your help.

**Comment by bvstone** [comment]
Check to make sure your FTP server is running on your IBM i.

WRKACTJOB JOB(QTFTP*)

**Comment by worksofliam** [comment]
After you have enabled FTP on your system, if you're still having issues try switching to `AutoActive` in the Connection Setting's FTP tab.

![image](https://user-images.githubusercontent.com/3708366/38367085-9f6810be-38d9-11e8-99b6-6bddba85487e.png)

**Comment by moege** [comment]
First, thanks for your fast help! 
I checked FTP and it is running on the system. I think I wouldn't be able to create a sourcemember if FTP wouldn't run, or?
So I switched to AutoActive in the Connection Setting's FTP tab, but unfortunately this didn't solve the problem too.
Do you have another tip for me?

**Comment by moege** [comment]
Sorry, I hadn't seen, that the settings-change needs a restart.
Now it works.

Thanks a lot guys!!

**Comment by worksofliam** [comment]
@moege 

Great, thanks!
