### ISSUE TITLE
Not able to open Source in ILEDITOR

### ISSUE THREAD

**Issue by NK11581** [WorksOfBarry/ILEditor#74]
Hi Liam,

I am a new user of ILEditor. I am able to create a source but not able to open a source. Even though I changed connection setting FTP -> AutoActive as per other blog still not opening existing source.

**Comment by worksofliam** [comment]
Please make sure you restart the client after you have changed the FTP setting.

**Comment by NK11581** [comment]
Hi Liam, Same error :-( 

Even though i tried on two systems with AutoActive selected and restarted ILEEditor. It gives same error "Unable to download member. Please check if it exists and you have access to the remote system:.One of them is at V7R1 and another at V6R1 . Is this can be an issue ?

**Comment by worksofliam** [comment]
@NK11581 ILEditor does not support 6.1. The next step would be:

1. Reproduce your steps 
2. Paste a copy of the Session FTP Log here. (Helo -> Session FTP Log)

I will close this issue. Please re-opening when your log has been pasted.
