### ISSUE TITLE
Response: 501 Character (?) not allowed in object name.

### ISSUE THREAD

**Issue by jannofett** [WorksOfBarry/ILEditor#75]
Greetings to all,
First of all, I want to thank everybody who's developing this project.
After trying some features, I've found out this thing:
if I try to open a file which begins with "§", ILEDITOR doesn't open it, giving me the error "Unable to download member [...]. Please check it exists and that you have access to the remote system".

I've tried all the connection options in the settings, but without improvements.

In the FTP log I've this text:

OpenRead("/QSYS.lib/TEST.lib/QRPGLESRC.file/�W0S02.mbr", ASCII, 0)
Command:  TYPE A
**Response: 200 Representation type is ASCII nonprint.**

OpenActiveDataStream(AutoActive, "RETR /QSYS.lib/TEST.lib/QRPGLESRC.file/�W0S02.mbr", 0)
Command:  EPRT |1|172.21.0.73|59392|
Response: 200 EPRT subcommand request successful.
Command:  RETR /QSYS.lib/TEST.lib/QRPGLESRC.file/�W0S02.mbr
**Response: 501 Character (?) not allowed in object name.**
Status:   Disposing FtpSocketStream...

CloseDataStream()

I leave below the images of what I'm speaking for:

![2018-04-16 14_10_11-ileditor 1 5 4 0 test](https://user-images.githubusercontent.com/38422628/38809211-11d8bd68-4183-11e8-8f68-d82e0ec00e48.png)
![2018-04-16 14_09_51-sessione a - 24 x 80](https://user-images.githubusercontent.com/38422628/38809213-14bff0c8-4183-11e8-883b-142f427f4ad7.png)

I know that I could rename the files in the SEU without having the problem of nonprintable inputs, but does another workaround exist, that I'm not aware of, to solve this thing?

**Comment by worksofliam** [comment]
Hi

I am afraid you will not be able to open members that use that character. This is just a general issue with FTP and nothing I can do to fix this. Of course, you will need to rename them in order to open them. I am curious as to why you'd use that character when naming members.

Sorry for any inconvenience. 
Liam

**Comment by jannofett** [comment]
It's because the software house I work with uses this way to name files done for other businesses, and there are a lot of them done in this way during the years, literally hundreds of hundreds. That's why I asked for the workaround. But thanks anyway.

Luca
