### ISSUE TITLE
Http/1.1 307 Temporary Redirect

### ISSUE THREAD

**Issue by Apsoftbe** [WorksOfBarry/ILEditor#76]
Error when installing product.
Http redirect is not allowed for application files and assemblies.

**Comment by worksofliam** [comment]
@Apsoftbe 

https://github.com/SMRFoundation/NodeXLBasic/issues/220

In the future, please be more elaborate when creating an issue.

Liam

**Comment by Apsoftbe** [comment]
Solution provided already tested out.
Default browser is Chrome.
Setup stops with message of http redirect is not allowed.
See attached log file (Dutch).
I think our security settings don't allow redirecting.
Is it possible to provide a setup file with libraries included.
Thanks in advance.
[ILeditor.log](https://github.com/WorksOfBarry/ILEditor/files/1938828/ILeditor.log)
