### ISSUE TITLE
RPG Conversion  in the Source menu is grayed out and no longer works.

### ISSUE THREAD

**Issue by XpPaul1** [WorksOfBarry/ILEditor#77]
RPG Conversion  in the Source/language tools menu is grayed out and no longer works.  I know that it worked on an earlier versions but I haven't tried it in a while.  I know that it doesn't work in version 1.6.0.0.

**Comment by worksofliam** [comment]
Hi. It has been disabled as of 1.6 because it needs some work - or maybe even a complete rewrite. 

Until then, it will be disabled in the release version. Please close this issue unless you have further questions.

Thanks!
