### ISSUE TITLE
Generate documentation from source

### ISSUE THREAD

**Issue by worksofliam** [WorksOfBarry/ILEditor#8]
I would like to see if it's possible to generate documentation based on comments. I'd either like to follow the JavaDoc syntax or something simiular to how C# is documented.

https://docs.microsoft.com/en-us/dotnet/csharp/codedoc

**Comment by bdietz400** [comment]
this is server side documentation.  http://systemideveloper.com/downloadRPGLEDOC.html
maybe something to help?

**Comment by worksofliam** [comment]
Note: give some priority after ILEditor meeting
