### ISSUE TITLE
Label tab with Library Source PF name (or option to do so)

### ISSUE THREAD

**Issue by bvstone** [WorksOfBarry/ILEditor#83]
Sometimes I come across code where the program name is the same as a /copy member or am working on two versions of the same program.

Program source is in QRPGLESRC

/COPY source is in QCOPYSRC (or something similar)

Both are type RPGLE or SQRPGLE.

So both tabs, when open, say PROGRAM.rpgle

Or, you could have the same program open in two different libraries (ie, test/developement)

Is there a way to add the library and source PF in to the tab?  

Or even as a hover over the tab make a popup that is:
library/sourcepf MBR(member)?

Thanks!

**Comment by worksofliam** [comment]
Hi!

Yes, this was also suggested to me recently at a conference. It will come in a soon release.

Liam

**Comment by worksofliam** [comment]
You can now hover over a tab in 1.6.1 and see the full path to the source.
