### ISSUE TITLE
FTP Port other than 21

### ISSUE THREAD

**Issue by bluezdood** [WorksOfBarry/ILEditor#84]
I currently have version 1.6.0.1 installed and the ability to use a FTP port number other than 21 is not available or not working.

ftp-control                              2121  tcp 
ftp-control                              2121  udp 
ftp-data                                  2120  tcp 
ftp-data                                  2120  udp

**Comment by worksofliam** [comment]
Hi! In the hostname have you tried this format? 

`hostname:port`?

Thanks!
Barry
