### ISSUE TITLE
Compiling a program results in application crash

### ISSUE THREAD

**Issue by mlstoppa** [WorksOfBarry/ILEditor#85]
When compiling any fixed-style SQLRPGLE sources with CRTBNDRPG command the process finishes successfully; when I do the same on a free-style RPGLE source, which by the way is CVTRPGFREE source from SourceForge, the application crashes after creating the object on the system. 
Details are:
Firma problema:
  Nome evento problema:	CLR20r3
  Firma problema 01:	ILEditor.exe
  Firma problema 02:	1.0.0.0
  Firma problema 03:	5af0cdd9
  Firma problema 04:	mscorlib
  Firma problema 05:	4.7.3130.0
  Firma problema 06:	5b175e25
  Firma problema 07:	1679
  Firma problema 08:	1d7
  Firma problema 09:	System.IO.IOException
  Versione SO:	6.1.7601.2.1.0.256.48
  ID impostazioni locali:	1040
  Informazioni aggiuntive 1:	0a9e
  Ulteriori informazioni 2:	0a9e372d3b4ad19135b953a78882e789
  Ulteriori informazioni 3:	0a9e
  Ulteriori informazioni 4:	0a9e372d3b4ad19135b953a78882e789
Sorry if details are in Italian but I count on self explaining order of comments, otherwise I'll translate them.

If the compilation process is done via SEU option 14, it finishes successfully too.

What can I check or do to solve the problem?

Thank you
Lucia

**Comment by worksofliam** [comment]
Hi @mlstoppa 

Must be something with the error listing parser.

Are you by any chance able to share some source code so I can try recreate it?

Thanks!

**Comment by mlstoppa** [comment]
Hi Liam,

Yes, this is the zip file with sources inside; CVTRPGFREE RPG Ile program is the source that raises the error. To compile it (SEU, option 14) you need CVTRPGFRP1 printer file already compiled and a few instructions: I changed variables names from @varname to zvarname, and created QRPGLESRC and QRPGLESRC2  source files. To have it compiled via IlEditor the library with sources and object must be added to library list, obviously.

By the way, I am trying to use this converter from fixed to free RPG form because it can convert all the members in source file, but it still has some issues that I am trying to solve. 

Thanks!
Lucia

[CVTRPGFREE_V1_1_7.zip](https://github.com/WorksOfBarry/ILEditor/files/2200446/CVTRPGFREE_V1_1_7.zip)

**Comment by mlstoppa** [comment]
Hi Liam, sorry for the delay: I am sure I have already written this post, but for some reason, it is not here so I write it again. 
Sure, I can share the source because it is open.

[CVTRPGFREE_V1_1_7.zip](https://github.com/WorksOfBarry/ILEditor/files/2226810/CVTRPGFREE_V1_1_7.zip)

Just a couple of hints to compile it: the one I can't compile is RPGLE source member named CVTRPGFREE . To have it compiled from SEU then PRTF CVTRPGFRP1 must exist and variables' names starting with @ must be changed to something else. Both QRPGLESRC and QRPGLESRC2 empty source files must exist, too.

Thanks

Lucia

**Comment by mlstoppa** [comment]
Hi Liam,
Did you have the chance to take a look at it?
Thanks!
Lucia

**Comment by worksofliam** [comment]
Hi @mlstoppa 

I haven't looked into it yet (sorry!), but I do plan on taking a look by the end of the week.

Liam

**Comment by worksofliam** [comment]
Hi @mlstoppa 

I am wondering if you can recreate this issue in a source file that is not as big as CVTRPGFREE. I am not able to recreate this issue.

Thanks!

**Comment by worksofliam** [comment]
Hi

I have had no response on this issue.

1.6.3 added something where crash dumps are made when the editor crashed. If that happens, please re-open and post the crash dump here.

Thanks!
Liam Barry
