### ISSUE TITLE
Posible failure when Libraries names are 10 char long

### ISSUE THREAD

**Issue by sanotto** [WorksOfBarry/ILEditor#86]
In IBMiUtils there is a convention to name temporary/work files as:

'S' + Lib and 'D'+lib

If lib is a library name of 10 chars long i.e. 'Lib4567890' the temporary files will get an eleven chars long name. That will trigger an error when creating objects.

Suggestion: Use a randon number instead of lib.
                    To aid in debuggingh you could  use CHGOBJD to save the library name in the object's TEXT description.

**Comment by worksofliam** [comment]
@sanotto Thanks for the bug report!

I will make a fix either late tonight - but you're more than welcome to open a PR.

Liam

**Comment by worksofliam** [comment]
Hi @sanotto 

I had a look through the code and it does seem like I am doing the correct substrings to make sure the object names are not more than 10 characters long. See the links below.

* https://github.com/WorksOfBarry/ILEditor/blob/master/ILEditor/Classes/IBMiUtils.cs#L95
* https://github.com/WorksOfBarry/ILEditor/blob/master/ILEditor/Classes/IBMiUtils.cs#L157

Thanks!
