### ISSUE TITLE
i18n issue 

### ISSUE THREAD

**Issue by sanotto** [WorksOfBarry/ILEditor#89]
![image](https://user-images.githubusercontent.com/11932376/43978942-707a04fc-9cbf-11e8-9dec-e521bb28e1bb.png)

When using accented letters (Spanish language)  ILE Editor does not encode those well.

The proposed fix in the image fixes it for my setup.  I suspect that the fix will also work in an  english setup but I can not be shure about it, so I submit this for you to evaluate.

**Comment by worksofliam** [comment]
Hi @sanotto 

Good find! 

I am also using this encoding in the SourceEditor component:

https://github.com/WorksOfBarry/ILEditor/blob/master/ILEditor/UserTools/SourceEditor.cs#L84

I will get this fixed up and released today.

Thanks!
Liam Barry

**Comment by worksofliam** [comment]
@sanotto 

ILEditor 1.6.3 has been released with this fix.

Please test and re-open if there is still an issue.

Thanks!

**Comment by sanotto** [comment]
I'll see to it asap!
